<?php

namespace De\Idrinth\TestGenerator\Test;

use De\Idrinth\TestGenerator\Implementations\NamespacePathMapper;
use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-01-23 at 18:59:09.
 */
class NamespacePathMapperTest extends TestCase
{
    /**
     * @var NamespacePathMapper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new NamespacePathMapper;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers De\Idrinth\TestGenerator\NamespacePathMapper::getTestNamespaceForNamespace
     * @todo   Implement testGetTestNamespaceForNamespace().
     */
    public function testGetTestNamespaceForNamespace()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers De\Idrinth\TestGenerator\NamespacePathMapper::getFileForNamespacedClass
     * @todo   Implement testGetFileForNamespacedClass().
     */
    public function testGetFileForNamespacedClass()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}