language: php
dist: trusty
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
matrix:
  include:
    - php: "5.3"
      dist: precise
git:
  depth: 3
script:
  - phpunit --testdox --bootstrap vendor/autoload.php test/